sudo: false

language: rust

matrix:
  include:
  - rust: 1.23.0
    env: PROTOBUF_VERSION=3.1.0
  - rust: stable
    env: PROTOBUF_VERSION=3.1.0
  - rust: beta
    env: PROTOBUF_VERSION=3.1.0
  - rust: nightly
    env: PROTOBUF_VERSION=3.1.0
  - rust: stable
    env: PROTOBUF_VERSION=2.6.1
  - rust: 1.23.0
    env: PROTOBUF_VERSION=3.1.0 RUST_PROTOBUF_FEATURES=with-bytes
  - rust: stable
    env: PROTOBUF_VERSION=3.1.0 RUST_PROTOBUF_FEATURES=with-bytes
  - rust: nightly
    env: PROTOBUF_VERSION=3.1.0 RUST_PROTOBUF_FEATURES=with-bytes

before_install:
  - ci/install-protobuf.sh
  - export PATH="/home/travis/bin:$PATH"
  - which protoc
  - protoc --version
  - export RUST_BACKTRACE=1

script:
  - rustc --version
  # Full rebuild with regenerate
  - PATH=/home/travis/bin:$PATH cargo build --manifest-path=protobuf-codegen/Cargo.toml
  # Regenerate only works when proto3
  - protobuf/regenerate_if_proto3.sh
  - cargo test --all
  # `cargo test --all --features=FFF` doesn't work if there are crates without feature `FFF`
  # hence the explicit list of tests
  - protobuf-test/test.sh
  - protobuf-codegen-pure-test/test.sh
  - protoc/test.sh
  - cargo build --all --all-targets

notifications:
  email:
    on_success: never

# vim: set ts=2 sw=2 et:
