sudo: false

language: rust

cache:
    directories:
    - $HOME/.ccache

matrix:
  include:
  - rust: 1.23.0
    env: PROTOBUF_VERSION=3.5.1
  - rust: stable
    env: PROTOBUF_VERSION=3.5.1
  - rust: beta
    env: PROTOBUF_VERSION=3.5.1
  - rust: 1.23.0
    env: PROTOBUF_VERSION=3.5.1 RUST_PROTOBUF_FEATURES=with-bytes,with-serde
  - rust: stable
    env: PROTOBUF_VERSION=3.5.1 RUST_PROTOBUF_FEATURES=with-bytes
  - rust: beta
    env: PROTOBUF_VERSION=3.5.1 RUST_PROTOBUF_FEATURES=with-serde
  - rust: nightly
    env: PROTOBUF_VERSION=3.5.1 RUST_PROTOBUF_FEATURES=with-bytes,with-serde
  - rust: stable
    env: PROTOBUF_VERSION=3.5.1 ON_WINDOWS=1
    os: windows
  allow_failures:
  - os: windows

before_install:
  - if [ -z "$ON_WINDOWS" ]; then ccache --zero-stats; fi
  - ci/install-protobuf.sh
  - if [ -z "$ON_WINDOWS" ]; then ccache --show-stats; fi
  - export PATH="$HOME/bin:$PATH"
  - which protoc
  - protoc --version
  - export RUST_BACKTRACE=1

script:
  - rustc --version
  - PATH=/home/travis/bin:$PATH cargo build --manifest-path=protobuf-codegen/Cargo.toml
  - protobuf/regenerate.sh
  - cargo test --all
  # `cargo test --all --features=FFF` doesn't work if there are crates without feature `FFF`
  # hence the explicit list of tests
  - protobuf-test/test.sh
  - protobuf-codegen-pure-test/test.sh
  - protoc/test.sh
  - cargo build --all --all-targets

notifications:
  email:
    on_success: never

# vim: set ts=2 sw=2 et:
