sudo: false

language: rust

matrix:
  include:
  - rust: stable
    env: PROTOBUF_VERSION=3.5.1
  - rust: beta
    env: PROTOBUF_VERSION=3.5.1
  - rust: nightly
    env: PROTOBUF_VERSION=3.5.1
  - rust: stable
    env: PROTOBUF_VERSION=3.5.1 RUST_PROTOBUF_FEATURES=with-bytes
  - rust: stable
    env: PROTOBUF_VERSION=3.5.1 RUST_PROTOBUF_FEATURES=with-serde
  - rust: nightly
    env: PROTOBUF_VERSION=3.5.1 RUST_PROTOBUF_FEATURES=with-serde,with-bytes

before_install:
  - ci/install-protobuf.sh
  - export PATH="/home/travis/bin:$PATH"
  - export LD_LIBRARY_PATH="/home/travis/lib"
  - which protoc
  - protoc --version
  - PKG_CONFIG_PATH="/home/travis/lib/pkgconfig" interop/cxx/compile.sh
  - export RUST_BACKTRACE=1

script:
  - rustc --version
  - protobuf/regenerate.sh
  - cargo test --all
  # `cargo test --all --features=FFF` doesn't work if there are crates without feature `FFF`
  # hence the explicit list of tests
  - protobuf-test/test.sh
  - protobuf-codegen-pure-test/test.sh
  - protoc/test.sh
  - cargo build --all --all-targets

notifications:
  email:
    on_success: never

# vim: set ts=2 sw=2 et:
