[workspace]
members = [
    "protoc",
    # Exclude test-protoc from the project, because it depends on binary
    #"protoc/test-protoc",
    "protoc-rust",
    "protobuf",
    "protobuf-codegen",
    "protobuf-codegen-pure",
    "protobuf-codegen-pure-test",
    "protobuf-test",
    "protobuf-test-common",
]
